"""Render a :class:`Report` to terminal, JSON or HTML."""

from __future__ import annotations

import html
import json
from typing import List

from .models import Report
from .utils import human_bytes

VERDICT_STYLE = {
    "CLEAN": ("bold green", "#2ecc71"), "LOW": ("bold green", "#27ae60"),
    "MEDIUM": ("bold yellow", "#f1c40f"), "HIGH": ("bold red", "#e67e22"),
    "CRITICAL": ("bold white on red", "#e74c3c"),
}
SEV_STYLE = {"critical": "red", "high": "red", "medium": "yellow", "low": "cyan", "info": "dim"}


def render_terminal(rep: Report, top: int = 10) -> None:
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table

    con = Console()
    style, _ = VERDICT_STYLE.get(rep.verdict, ("bold", ""))
    header = (
        f"[{style}]{rep.verdict}[/]\n"
        f"[bold]{rep.path}[/]\n"
        f"{rep.packets} packets · {human_bytes(rep.bytes)} · {rep.duration:.1f}s"
    )
    con.print(Panel(header, title="pcapsleuth", border_style=style.split()[-1]))

    proto = " ".join(f"{k}:{v}" for k, v in sorted(rep.proto_counts.items(), key=lambda x: -x[1]))
    app = " ".join(f"{k}:{v}" for k, v in sorted(rep.app_counts.items(), key=lambda x: -x[1]))
    con.print(f"[bold]Protocols[/] {proto}")
    if app:
        con.print(f"[bold]App[/]       {app}")

    if rep.talkers:
        t = Table(title="Top talkers", expand=True)
        t.add_column("Host", style="cyan", no_wrap=True)
        t.add_column("Bytes", justify="right")
        t.add_column("Packets", justify="right")
        for ip, b, p in rep.talkers[:top]:
            t.add_row(ip, human_bytes(b), str(p))
        con.print(t)

    if rep.findings:
        t = Table(title=f"Detections ({len(rep.findings)})", expand=True, show_lines=True)
        t.add_column("Sev", width=8)
        t.add_column("Finding", style="bold")
        t.add_column("MITRE", style="cyan", no_wrap=True)
        for f in rep.findings:
            sev = SEV_STYLE.get(f.severity, "white")
            t.add_row(f"[{sev}]{f.severity}[/]", f"{f.title}\n[dim]{f.detail}[/]", ", ".join(f.ttps))
        con.print(t)
    else:
        con.print("[green]✓ No suspicious patterns detected.[/]")

    total_iocs = sum(len(v) for v in rep.iocs.values())
    if total_iocs:
        t = Table(title=f"IOCs ({total_iocs})", expand=True)
        t.add_column("Type", width=14, style="bold")
        t.add_column("Indicator")
        for label, items in rep.iocs.items():
            for it in items[:top]:
                t.add_row(label, it)
        con.print(t)


def render_json(rep: Report, iocs_only: bool = False) -> str:
    return json.dumps(rep.iocs if iocs_only else rep.to_dict(), indent=2)


def render_markdown(rep: Report) -> str:
    L: List[str] = [f"# PCAP Triage — `{rep.path}`", "",
                    f"**Verdict:** `{rep.verdict}` · {rep.packets} packets · {human_bytes(rep.bytes)} · {rep.duration:.1f}s", ""]
    if rep.findings:
        L += ["## Detections", "", "| Sev | Finding | MITRE | Detail |", "| --- | --- | --- | --- |"]
        for f in rep.findings:
            detail = f.detail.replace("|", "\\|")
            ttps = ", ".join(f.ttps)
            L.append(f"| {f.severity} | {f.title} | {ttps} | {detail} |")
        L.append("")
    if any(rep.iocs.values()):
        L += ["## IOCs", ""]
        for label, items in rep.iocs.items():
            if items:
                L.append(f"**{label}**")
                L += [f"- `{i}`" for i in items]
                L.append("")
    L += ["---", "_Generated by [pcapsleuth](https://github.com/defamp/pcapsleuth)._"]
    return "\n".join(L)


def render_html(rep: Report) -> str:
    _, colour = VERDICT_STYLE.get(rep.verdict, ("", "#555"))
    esc = html.escape
    find_rows = "".join(
        f"<tr><td class='sev sev-{f.severity}'>{f.severity}</td><td><b>{esc(f.title)}</b>"
        f"<div class='dim'>{esc(f.detail)}</div></td><td><code>{esc(', '.join(f.ttps))}</code></td></tr>"
        for f in rep.findings)
    talk_rows = "".join(
        f"<tr><td><code>{esc(ip)}</code></td><td>{human_bytes(b)}</td><td>{p}</td></tr>"
        for ip, b, p in rep.talkers[:15])
    ioc_blocks = "".join(
        f"<h4>{esc(k)}</h4><ul>" + "".join(f"<li><code>{esc(i)}</code></li>" for i in v) + "</ul>"
        for k, v in rep.iocs.items() if v)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>pcapsleuth — {esc(rep.path)}</title><style>
 :root{{--bg:#0a0e1a;--card:#151c2e;--fg:#e6edf7;--dim:#9aa8c2;--line:#243049;--accent:{colour};}}
 body{{margin:0;background:var(--bg);color:var(--fg);font:15px/1.6 -apple-system,Segoe UI,Roboto,sans-serif;}}
 .wrap{{max-width:900px;margin:0 auto;padding:24px 16px;}}
 .verdict{{display:inline-block;padding:4px 14px;border-radius:6px;font-weight:800;background:var(--accent);color:#111;}}
 .card{{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin:16px 0;}}
 table{{width:100%;border-collapse:collapse;}} th,td{{text-align:left;padding:7px 8px;border-bottom:1px solid var(--line);vertical-align:top;}}
 th{{color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:.04em;}}
 code{{background:#0b0f1c;padding:1px 5px;border-radius:4px;font-size:13px;}} .dim{{color:var(--dim);font-size:13px;}}
 .sev{{font-weight:800;text-transform:uppercase;font-size:11px;}} .sev-critical,.sev-high{{color:#f87171;}} .sev-medium{{color:#fbbf24;}} .sev-low{{color:#38bdf8;}}
</style></head><body><div class="wrap">
 <h1>🛰️ {esc(rep.path)}</h1>
 <p><span class="verdict">{esc(rep.verdict)}</span> &nbsp; {rep.packets} packets · {human_bytes(rep.bytes)} · {rep.duration:.1f}s</p>
 {f'<div class="card"><h3>Detections</h3><table><tr><th>Sev</th><th>Finding</th><th>MITRE</th></tr>{find_rows}</table></div>' if find_rows else '<div class="card">No suspicious patterns detected.</div>'}
 <div class="card"><h3>Top talkers</h3><table><tr><th>Host</th><th>Bytes</th><th>Packets</th></tr>{talk_rows}</table></div>
 {f'<div class="card"><h3>IOCs</h3>{ioc_blocks}</div>' if ioc_blocks else ''}
 <footer class="dim" style="margin-top:20px">Generated by pcapsleuth.</footer>
</div></body></html>"""
